name: study_sphere_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.0.2
  file_picker: ^5.2.11
  file_saver: ^0.1.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.19
  flutter_progress_hud: ^2.0.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.2.1
  formz: ^0.5.0+1
  go_router: ^6.2.0
  google_fonts: ^4.0.4
  heroicons: ^0.8.0
  html_editor_enhanced: ^2.5.1
  http: ^0.13.5
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  intro_slider: ^4.2.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  responsive_builder: ^0.6.4
  scroll_date_picker: ^3.7.0
  shared_preferences: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^2.0.1
  table_calendar: ^3.0.9
  universal_html: ^2.0.8
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4

flutter_icons:
  android: true
  image_path: "assets/logo/ic_launcher.png"
  adaptive_icon_background: "assets/logo/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/logo/ic_launcher_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/logo.png

  android_12:
    image: assets/logo/logo.png

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/not-class.svg
    - assets/images/not-work.jpg
    - assets/images/not-board.jpg
    - assets/images/no-task.jpg
    - assets/images/pdf.svg
    - assets/images/not-todo.svg
    - assets/images/not-todo.svg
    - assets/images/beta.svg
    - assets/images/not-connection.png
    - assets/images/not-connection.svg
    - assets/intro/1.png
    - assets/intro/2.png
    - assets/intro/3.png
    - assets/intro/4.png
    - assets/logo/logo.png
    - assets/logo/logo_white.png
    - assets/
    - assets/svgs/
